baseurl = "https://jocobtt.github.io"
DefaultContentLanguage = "en"
title = "Jacob Braswell"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
googleAnalytics = 'G-QRKRLKN0FZ'


[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "MLOps Engineer & Tech Enthusiast"
  mainSections = ["post","posts"]
  logo = "img/me.png" # Expecting square dimensions
  favicon = "img/robot_.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Jacob Braswell"
  email = "jacob.braswell00@gmail.com"
  github = "jocobtt"
  linkedin = "jacob-braswell"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Connect"
    url = "connect"
    weight = 3

[[menu.main]]
    name = "About"
    url = "about"
    weight = 3

#[[menu.main]]
#    name = "Portfolio"
#    url = "portfolio"
#    weight = 3

